### ISSUE TITLE
Allow specifying a recording file via query parameter

### ISSUE THREAD

**Issue by ngokevin** [dmarcos/aframe-motion-capture-components#6]
Use cases:

- I want to share a link of the recording, but have the original scene still be playable.
- I want to quickly switch between recordings for testing purposes, without having to modify my code.

```https://foo.bar/aframe.html?webvr-recording=recordings/baz.json```
```https://foo.bar/aframe.html?webvr-recording=recordings/qux.json```

**Comment by dmarcos** [comment]
yep

**Comment by ngokevin** [comment]
https://github.com/dmarcos/aframe-motion-capture/pull/12
