### ISSUE TITLE
Recording/replayer UI component

### ISSUE THREAD

**Issue by ngokevin** [dmarcos/aframe-motion-capture-components#7]
A component that creates a UI for recording and replaying.

Actions may include:

- Record
- Stop recording
- Specify filename of downloaded recording
- Replay recording
- Stop replay of recording
- Select a file to play

Super difficult actions in the far future may include:

- Scrubbing back and forth
- Pause and resume replay

**Comment by dmarcos** [comment]
Yep, should be part of this repo or part of the inspector

**Comment by ngokevin** [comment]
We can provide a simple one in this repo for now to prototype and get the events infrastructure in place. We can start using it immediately, and then later it'll be easy to create one for Inspector.

**Comment by ngokevin** [comment]
Moving to https://github.com/aframevr/aframe-inspector/pull/498
